name: example
description: An application to demonstrate the work of isolator.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  isolator:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
